sudo: required
services:
    - docker

before_install:
    - docker build -t richardkl/react-test -f ./client/Dockerfile.dev ./client

script:
    # The -e flag stands for environment
    - docker run -e CI=true richardkl/react-test npm run test

after_success:
    - docker build -t richardkl/multi-client ./client
    - docker build -t richardkl/multi-nginx ./nginx
    - docker build -t richardkl/multi-server ./server
    - docker build -t richardkl/multi-worker ./worker

    # Login to docker CLI. ENV variables are stored in the travis dashboard
    # The '|' is used to get the output on the left side and use that for the command on the right side
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push images to docker hub
    - docker push richardkl/multi-client
    - docker push richardkl/multi-nginx
    - docker push richardkl/multi-server
    - docker push richardkl/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: eu-west-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-west-2-231061592073
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY

