FROM nginx
# When you include the filename at the end of your command,
# it will overwrite any files with that name. Usefull the overwrite the default
COPY ./default.conf /etc/nginx/conf.d/default.conf
